# Generated by Django 3.0.6 on 2020-06-13 08:57

import common.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import portal.models
import private_storage.fields
import private_storage.storage.files
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtectionPatternProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=80)),
                ("pattern", models.CharField(max_length=80)),
                ("expires_on", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "protection_pattern_profile_view",
                "ordering": ["description"],
                "managed": False,
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Affiliation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("EDU", "Education"),
                            ("EMP", "Employment"),
                            ("MEM", "Membership"),
                            ("SER", "service"),
                        ],
                        max_length=10,
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=100, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("put_code", models.PositiveIntegerField(blank=True, editable=False, null=True)),
            ],
            options={"db_table": "affiliation",},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ApplicationDecision",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(max_length=2, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=80)),
                ("definition", models.TextField(max_length=200)),
            ],
            options={"db_table": "application_decision", "ordering": ["description"],},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="prestigious prize or medal"),
                ),
            ],
            options={"db_table": "award",},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CareerStage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(max_length=2, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=40)),
                ("definition", models.TextField(max_length=1000)),
            ],
            options={"db_table": "career_stage", "ordering": ["code"],},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Ethnicity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(max_length=5, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=40)),
                ("level_three_code", models.CharField(max_length=3)),
                ("level_three_description", models.CharField(max_length=40)),
                ("level_two_code", models.CharField(max_length=2)),
                ("level_two_description", models.CharField(max_length=40)),
                ("level_one_code", models.CharField(max_length=20)),
                ("level_one_description", models.CharField(max_length=40)),
                ("definition", models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={"db_table": "ethnicity", "ordering": ["code"],},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="FieldOfResearch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(max_length=6, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=120, verbose_name="description")),
                ("four_digit_code", models.CharField(max_length=4)),
                ("four_digit_description", models.CharField(max_length=60)),
                ("two_digit_code", models.CharField(max_length=2)),
                ("two_digit_description", models.CharField(max_length=60)),
                ("definition", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={"db_table": "field_of_research",},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="FieldOfStudy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "code",
                    models.CharField(
                        max_length=6, primary_key=True, serialize=False, verbose_name="code"
                    ),
                ),
                ("description", models.CharField(max_length=100, verbose_name="description")),
                ("four_digit_code", models.CharField(max_length=4)),
                ("four_digit_description", models.CharField(max_length=100)),
                ("two_digit_code", models.CharField(max_length=2)),
                ("two_digit_description", models.CharField(max_length=60)),
                ("definition", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={"db_table": "field_of_study", "ordering": ["description"],},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="IwiGroup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(max_length=4, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=80)),
                ("parent_code", models.CharField(max_length=2)),
                ("parent_description", models.CharField(max_length=100)),
                ("definition", models.TextField(max_length=200)),
            ],
            options={"db_table": "iwi_group", "ordering": ["code"],},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(max_length=3, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=100)),
                ("definition", models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={"db_table": "language", "ordering": ["code"],},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("identifier", models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={"db_table": "organisation",},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OrgIdentifierType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(max_length=2, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=20)),
                ("definition", models.TextField(max_length=200)),
            ],
            options={
                "verbose_name": "organisation identifier type",
                "db_table": "org_identifier_type",
                "ordering": ["code"],
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PersonIdentifierType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(blank=True, max_length=2, null=True)),
                ("description", models.CharField(max_length=40)),
                ("definition", models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={"db_table": "person_identifier_type", "ordering": ["description"],},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "gender",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Undisclosed"),
                            (1, "Male"),
                            (2, "Female"),
                            (3, "Gender diverse"),
                        ],
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("is_ethnicities_completed", models.BooleanField(default=True)),
                (
                    "education_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "No Qualification"),
                            (1, "Level 1 Certificate"),
                            (2, "Level 2 Certificate"),
                            (3, "Level 3 Certificate"),
                            (4, "Level 4 Certificate"),
                            (5, "Level 5 Diploma/Certificate"),
                            (6, "Level 6 Graduate Certificate, Level 6 Diploma/Certificate"),
                            (
                                7,
                                "Bachelor Degree, Level 7 Graduate Diploma/Certificate, Level 7 Diploma/ Certificate",
                            ),
                            (8, "Postgraduate Diploma/Certificate, Bachelor Honours"),
                            (9, "Masters Degree"),
                            (10, "Doctorate Degree"),
                            (23, "Overseas Secondary School Qualification"),
                            (94, "Don't Know"),
                            (95, "Refused to Answer"),
                            (96, "Repeated Value"),
                            (97, "Response Unidentifiable"),
                            (98, "Response Outside Scope"),
                            (99, "Not Stated"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "employment_status",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Paid employee"),
                            (2, "Employer"),
                            (3, "Self-employed and without employees"),
                            (4, "Unpaid family worker"),
                            (5, "Not stated"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "primary_language_spoken",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Afrikaans", "Afrikaans"),
                            ("Arabic", "Arabic"),
                            ("Bahasa Indonesia", "Bahasa Indonesia"),
                            ("Chinese (not further defined)", "Chinese (not further defined)"),
                            ("Cook Islands Māori", "Cook Islands Māori"),
                            ("Dutch", "Dutch"),
                            ("English (New Zealand English)", "English (New Zealand English)"),
                            ("Fijian", "Fijian"),
                            ("French", "French"),
                            ("German", "German"),
                            ("Gujarati", "Gujarati"),
                            ("Hindi", "Hindi"),
                            ("Italian", "Italian"),
                            ("Japanese", "Japanese"),
                            ("Khmer", "Khmer"),
                            ("Korean", "Korean"),
                            ("Malayalam", "Malayalam"),
                            ("Malaysian", "Malaysian"),
                            ("Mandarin Chinese", "Mandarin Chinese"),
                            ("Māori", "Māori"),
                            ("Min Chinese", "Min Chinese"),
                            ("New Zealand Sign Language", "New Zealand Sign Language"),
                            ("Niuean", "Niuean"),
                            ("Persian", "Persian"),
                            ("Punjabi", "Punjabi"),
                            ("Russian", "Russian"),
                            ("Samoan", "Samoan"),
                            ("Serbo-Croatian", "Serbo-Croatian"),
                            ("Sinhala", "Sinhala"),
                            ("Spanish", "Spanish"),
                            ("Tagalog", "Tagalog"),
                            ("Tamil", "Tamil"),
                            ("Thai", "Thai"),
                            ("Tongan", "Tongan"),
                            ("Urdu", "Urdu"),
                            ("Vietnamese", "Vietnamese"),
                            ("Yue Chinese (Cantonese)", "Yue Chinese (Cantonese)"),
                            ("Other", "Other"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                ("is_iwi_groups_completed", models.BooleanField(default=True)),
                (
                    "is_accepted",
                    models.BooleanField(default=False, verbose_name="Privace Policy Accepted"),
                ),
                ("is_career_stages_completed", models.BooleanField(default=False)),
                ("is_external_ids_completed", models.BooleanField(default=False)),
                ("has_protection_patterns", models.BooleanField(default=False)),
                ("is_employments_completed", models.BooleanField(default=False)),
                ("is_professional_bodies_completed", models.BooleanField(default=False)),
                ("is_academic_records_completed", models.BooleanField(default=False)),
                ("is_recognitions_completed", models.BooleanField(default=False)),
                ("is_cvs_completed", models.BooleanField(default=False)),
                (
                    "affiliations",
                    models.ManyToManyField(
                        blank=True, through="portal.Affiliation", to="portal.Organisation"
                    ),
                ),
            ],
            options={"db_table": "profile",},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProtectionPattern",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=80)),
                ("description_en", models.CharField(max_length=80, null=True)),
                ("description_mi", models.CharField(max_length=80, null=True)),
                ("pattern", models.CharField(max_length=80)),
            ],
            options={"db_table": "protection_pattern", "ordering": ["description"],},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(blank=True, max_length=2, null=True)),
                ("description", models.CharField(max_length=100)),
                ("definition", models.TextField(blank=True, max_length=100, null=True)),
                (
                    "is_nzqf",
                    models.BooleanField(
                        default=True,
                        verbose_name="the New Zealand Qualifications Framework Qualification level",
                    ),
                ),
            ],
            options={"db_table": "qualification", "ordering": ["definition"],},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("opens_on", models.DateField(blank=True, null=True)),
                ("closes_on", models.DateField(blank=True, null=True)),
            ],
            options={"db_table": "round",},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("email", models.EmailField(max_length=120)),
                ("name", models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={"db_table": "subscription",},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Scheme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.CharField(max_length=100)),
                ("title_en", models.CharField(max_length=100, null=True)),
                ("title_mi", models.CharField(max_length=100, null=True)),
                (
                    "guidelines",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="guideline link URL"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="short description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="short description"
                    ),
                ),
                (
                    "description_mi",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="short description"
                    ),
                ),
                (
                    "research_summary_required",
                    models.BooleanField(default=False, verbose_name="research summary required"),
                ),
                (
                    "team_can_apply",
                    models.BooleanField(default=False, verbose_name="can be submitted by a team"),
                ),
                ("presentation_required", models.BooleanField(default=False)),
                ("cv_required", models.BooleanField(default=True, verbose_name="CVs required")),
                (
                    "pid_required",
                    models.BooleanField(default=True, verbose_name="photo ID required"),
                ),
                ("animal_ethics_required", models.BooleanField(default=False)),
                (
                    "current_round",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="portal.Round",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        db_table="scheme_group",
                        to="auth.Group",
                        verbose_name="who starts",
                    ),
                ),
            ],
            options={"db_table": "scheme",},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AddField(
            model_name="round",
            name="scheme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rounds",
                to="portal.Scheme",
            ),
        ),
        migrations.CreateModel(
            name="Recognition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "recognized_in",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="year of recognition"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="amount",
                    ),
                ),
                ("put_code", models.PositiveIntegerField(blank=True, editable=False, null=True)),
                (
                    "award",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.Award",
                        verbose_name="award",
                    ),
                ),
                (
                    "awarded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.Organisation",
                        verbose_name="awarded by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recognitions",
                        to="portal.Profile",
                    ),
                ),
            ],
            options={"db_table": "recognition",},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProfilePersonIdentifier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("value", models.CharField(max_length=20)),
                ("put_code", models.PositiveIntegerField(blank=True, editable=False, null=True)),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="portal.PersonIdentifierType",
                        verbose_name="type",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.Profile"
                    ),
                ),
            ],
            options={"db_table": "profile_person_identifier",},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProfileCareerStage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "year_achieved",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                (
                    "career_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.CareerStage"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.Profile"
                    ),
                ),
            ],
            options={"db_table": "profile_career_stage",},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AddField(
            model_name="profile",
            name="career_stages",
            field=models.ManyToManyField(
                blank=True, through="portal.ProfileCareerStage", to="portal.CareerStage"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="ethnicities",
            field=models.ManyToManyField(
                blank=True, db_table="profile_ethnicity", to="portal.Ethnicity"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="external_ids",
            field=models.ManyToManyField(
                blank=True,
                through="portal.ProfilePersonIdentifier",
                to="portal.PersonIdentifierType",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="iwi_groups",
            field=models.ManyToManyField(
                blank=True, db_table="profile_iwi_group", to="portal.IwiGroup"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="languages_spoken",
            field=models.ManyToManyField(
                blank=True, db_table="profile_language", to="portal.Language"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="identifier_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portal.OrgIdentifierType",
            ),
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "token",
                    models.CharField(
                        default=portal.models.get_unique_invitation_token,
                        max_length=42,
                        unique=True,
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email address")),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=150)),
                (
                    "organisation",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="organisation"
                    ),
                ),
                (
                    "status",
                    portal.models.StateField(
                        choices=[
                            ("draft", "draft"),
                            ("submitted", "submitted"),
                            ("accepted", "accepted"),
                            ("expired", "expired"),
                        ],
                        default="draft",
                        max_length=100,
                        no_check_for_status=True,
                    ),
                ),
                (
                    "submitted_at",
                    model_utils.fields.MonitorField(
                        blank=True, default=None, monitor="status", null=True, when={"submitted"}
                    ),
                ),
                (
                    "accepted_at",
                    model_utils.fields.MonitorField(
                        blank=True, default=None, monitor="status", null=True, when={"accepted"}
                    ),
                ),
                (
                    "expired_at",
                    model_utils.fields.MonitorField(
                        blank=True, default=None, monitor="status", null=True, when={"expired"}
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.Organisation",
                        verbose_name="organisation",
                    ),
                ),
            ],
            options={"db_table": "invitation",},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRound",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("opens_on", models.DateField(blank=True, null=True)),
                ("closes_on", models.DateField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.Scheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical round",
                "db_table": "round_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProfile",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "gender",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Undisclosed"),
                            (1, "Male"),
                            (2, "Female"),
                            (3, "Gender diverse"),
                        ],
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("is_ethnicities_completed", models.BooleanField(default=True)),
                (
                    "education_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "No Qualification"),
                            (1, "Level 1 Certificate"),
                            (2, "Level 2 Certificate"),
                            (3, "Level 3 Certificate"),
                            (4, "Level 4 Certificate"),
                            (5, "Level 5 Diploma/Certificate"),
                            (6, "Level 6 Graduate Certificate, Level 6 Diploma/Certificate"),
                            (
                                7,
                                "Bachelor Degree, Level 7 Graduate Diploma/Certificate, Level 7 Diploma/ Certificate",
                            ),
                            (8, "Postgraduate Diploma/Certificate, Bachelor Honours"),
                            (9, "Masters Degree"),
                            (10, "Doctorate Degree"),
                            (23, "Overseas Secondary School Qualification"),
                            (94, "Don't Know"),
                            (95, "Refused to Answer"),
                            (96, "Repeated Value"),
                            (97, "Response Unidentifiable"),
                            (98, "Response Outside Scope"),
                            (99, "Not Stated"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "employment_status",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Paid employee"),
                            (2, "Employer"),
                            (3, "Self-employed and without employees"),
                            (4, "Unpaid family worker"),
                            (5, "Not stated"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "primary_language_spoken",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Afrikaans", "Afrikaans"),
                            ("Arabic", "Arabic"),
                            ("Bahasa Indonesia", "Bahasa Indonesia"),
                            ("Chinese (not further defined)", "Chinese (not further defined)"),
                            ("Cook Islands Māori", "Cook Islands Māori"),
                            ("Dutch", "Dutch"),
                            ("English (New Zealand English)", "English (New Zealand English)"),
                            ("Fijian", "Fijian"),
                            ("French", "French"),
                            ("German", "German"),
                            ("Gujarati", "Gujarati"),
                            ("Hindi", "Hindi"),
                            ("Italian", "Italian"),
                            ("Japanese", "Japanese"),
                            ("Khmer", "Khmer"),
                            ("Korean", "Korean"),
                            ("Malayalam", "Malayalam"),
                            ("Malaysian", "Malaysian"),
                            ("Mandarin Chinese", "Mandarin Chinese"),
                            ("Māori", "Māori"),
                            ("Min Chinese", "Min Chinese"),
                            ("New Zealand Sign Language", "New Zealand Sign Language"),
                            ("Niuean", "Niuean"),
                            ("Persian", "Persian"),
                            ("Punjabi", "Punjabi"),
                            ("Russian", "Russian"),
                            ("Samoan", "Samoan"),
                            ("Serbo-Croatian", "Serbo-Croatian"),
                            ("Sinhala", "Sinhala"),
                            ("Spanish", "Spanish"),
                            ("Tagalog", "Tagalog"),
                            ("Tamil", "Tamil"),
                            ("Thai", "Thai"),
                            ("Tongan", "Tongan"),
                            ("Urdu", "Urdu"),
                            ("Vietnamese", "Vietnamese"),
                            ("Yue Chinese (Cantonese)", "Yue Chinese (Cantonese)"),
                            ("Other", "Other"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                ("is_iwi_groups_completed", models.BooleanField(default=True)),
                (
                    "is_accepted",
                    models.BooleanField(default=False, verbose_name="Privace Policy Accepted"),
                ),
                ("is_career_stages_completed", models.BooleanField(default=False)),
                ("is_external_ids_completed", models.BooleanField(default=False)),
                ("has_protection_patterns", models.BooleanField(default=False)),
                ("is_employments_completed", models.BooleanField(default=False)),
                ("is_professional_bodies_completed", models.BooleanField(default=False)),
                ("is_academic_records_completed", models.BooleanField(default=False)),
                ("is_recognitions_completed", models.BooleanField(default=False)),
                ("is_cvs_completed", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical profile",
                "db_table": "profile_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOrganisation",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=200)),
                ("identifier", models.CharField(blank=True, max_length=24, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "identifier_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.OrgIdentifierType",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical organisation",
                "db_table": "organisation_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalApplication",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("is_team_application", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=512)),
                ("first_name", models.CharField(max_length=30)),
                (
                    "middle_names",
                    models.CharField(
                        blank=True,
                        help_text="Comma separated list of middle names",
                        max_length=280,
                        null=True,
                        verbose_name="middle names",
                    ),
                ),
                ("last_name", models.CharField(max_length=150)),
                ("organisation", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=80)),
                ("postal_address", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=80)),
                ("postcode", models.CharField(max_length=4)),
                (
                    "daytime_phone",
                    models.CharField(max_length=12, verbose_name="daytime phone numbrer"),
                ),
                (
                    "mobile_phone",
                    models.CharField(max_length=12, verbose_name="mobild phone number"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email address"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.Organisation",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.Round",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical application",
                "db_table": "application_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAffiliation",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("EDU", "Education"),
                            ("EMP", "Employment"),
                            ("MEM", "Membership"),
                            ("SER", "service"),
                        ],
                        max_length=10,
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=100, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("put_code", models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.Organisation",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical affiliation",
                "db_table": "affiliation_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="CurriculumVitae",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, null=True, verbose_name="title"),
                ),
                (
                    "file",
                    private_storage.fields.PrivateFileField(
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.Profile"
                    ),
                ),
            ],
            options={"db_table": "curriculum_vitae",},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_team_application", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=512)),
                ("first_name", models.CharField(max_length=30)),
                (
                    "middle_names",
                    models.CharField(
                        blank=True,
                        help_text="Comma separated list of middle names",
                        max_length=280,
                        null=True,
                        verbose_name="middle names",
                    ),
                ),
                ("last_name", models.CharField(max_length=150)),
                ("organisation", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=80)),
                ("postal_address", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=80)),
                ("postcode", models.CharField(max_length=4)),
                (
                    "daytime_phone",
                    models.CharField(max_length=12, verbose_name="daytime phone numbrer"),
                ),
                (
                    "mobile_phone",
                    models.CharField(max_length=12, verbose_name="mobild phone number"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email address"),
                ),
                (
                    "org",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.Organisation",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="portal.Round",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "application",},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AddField(
            model_name="affiliation",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="portal.Organisation",
                verbose_name="organisation",
            ),
        ),
        migrations.AddField(
            model_name="affiliation",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="portal.Profile"
            ),
        ),
        migrations.CreateModel(
            name="AcademicRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "start_year",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1960),
                            django.core.validators.MaxValueValidator(2099),
                        ],
                    ),
                ),
                ("conferred_on", models.DateField(blank=True, null=True)),
                ("research_topic", models.CharField(blank=True, max_length=80, null=True)),
                ("put_code", models.PositiveIntegerField(blank=True, editable=False, null=True)),
                (
                    "awarded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.Organisation"
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.FieldOfStudy",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_records",
                        to="portal.Profile",
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="portal.Qualification",
                    ),
                ),
            ],
            options={"db_table": "academic_record",},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProfileProtectionPattern",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("expires_on", models.DateField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_protection_patterns",
                        to="portal.Profile",
                    ),
                ),
                (
                    "protection_pattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_protection_patterns",
                        to="portal.ProtectionPattern",
                    ),
                ),
            ],
            options={
                "db_table": "profile_protection_pattern",
                "unique_together": {("profile", "protection_pattern")},
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
    ]
