# Generated by Django 3.1.8 on 2021-04-19 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schemeapplication",
            options={"managed": False},
        ),
        migrations.AddField(
            model_name="subscription",
            name="is_confirmed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="maillog",
            name="recipient",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterModelTable(
            name="schemeapplication",
            table=None,
        ),
    ]
