# Generated by Django 3.2.3 on 2021-05-14 09:36

from django.db import migrations, models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_auto_20210421_1545"),
    ]

    operations = [
        migrations.AddField(
            model_name="protectionpattern",
            name="comment",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="protectionpattern",
            name="comment_en",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="protectionpattern",
            name="comment_mi",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="testimony",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                help_text="Please upload your endorsement, testimony, or feedback",
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="",
                verbose_name="endorsement, testimony, or feedback",
            ),
        ),
        migrations.AlterModelTable(
            name="protectionpatternprofile",
            table=None,
        ),
    ]
