# Generated by Django 3.0.7 on 2020-06-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemeApplicationGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={"db_table": "scheme_group", "managed": False,},
        ),
    ]
