# Generated by Django 3.2.3 on 2021-05-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_auto_20210525_1910"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalround",
            name="title_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="title_mi",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
