# Generated by Django 3.0.7 on 2020-06-28 00:49

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0006_auto_20200626_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(max_length=120)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('middle_names', models.CharField(blank=True, help_text='Comma separated list of middle names', max_length=280, null=True, verbose_name='middle names')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('has_testifed', models.BooleanField(default=False)),
                ('testified_at', models.DateField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referees', to='portal.Application')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referee',
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
    ]
