# Generated by Django 3.2.3 on 2021-05-27 23:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import portal.models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_auto_20210525_1936"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConvertedFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "file",
                    private_storage.fields.PrivateFileField(
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="historicalround",
            name="application_template",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["doc", "docx", "dot", "dotx", "docm", "dotm", "docb"]
                    )
                ],
                verbose_name="Application Template",
            ),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="nomination_template",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["doc", "docx", "dot", "dotx", "docm", "dotm", "docb"]
                    )
                ],
                verbose_name="Nomination Template",
            ),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="referee_template",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["doc", "docx", "dot", "dotx", "docm", "dotm", "docb"]
                    )
                ],
                verbose_name="Referee Template",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="application_template",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=portal.models.round_template_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["doc", "docx", "dot", "dotx", "docm", "dotm", "docb"]
                    )
                ],
                verbose_name="Application Template",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="nomination_template",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=portal.models.round_template_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["doc", "docx", "dot", "dotx", "docm", "dotm", "docb"]
                    )
                ],
                verbose_name="Nomination Template",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="referee_template",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=portal.models.round_template_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["doc", "docx", "dot", "dotx", "docm", "dotm", "docb"]
                    )
                ],
                verbose_name="Referee Template",
            ),
        ),
        migrations.AlterField(
            model_name="historicalprofile",
            name="has_protection_patterns",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="has_protection_patterns",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="application",
            name="converted_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portal.convertedfile",
            ),
        ),
        migrations.AddField(
            model_name="curriculumvitae",
            name="converted_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portal.convertedfile",
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="converted_file",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.convertedfile",
            ),
        ),
        migrations.AddField(
            model_name="historicalnomination",
            name="converted_file",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.convertedfile",
            ),
        ),
        migrations.AddField(
            model_name="nomination",
            name="converted_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portal.convertedfile",
            ),
        ),
        migrations.AddField(
            model_name="testimony",
            name="converted_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portal.convertedfile",
            ),
        ),
    ]
