# Generated by Django 3.0.7 on 2020-06-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_referee"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE application ADD COLUMN summary text NULL;
            ALTER TABLE application_history ADD COLUMN summary text NULL;
            """,
            "",
            state_operations=[
                migrations.AddField(
                    model_name="application",
                    name="summary",
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="historicalapplication",
                    name="summary",
                    field=models.TextField(blank=True, null=True),
                ),
            ],
        )
    ]
