# Generated by Django 3.0.7 on 2020-07-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20200630_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
