# Generated by Django 3.2.4 on 2021-07-16 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0009_auto_20210615_1254"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conflictofinterest",
            options={"verbose_name_plural": "conflicts of interest"},
        ),
        migrations.AlterModelOptions(
            name="ethnicity",
            options={"ordering": ["code"], "verbose_name_plural": "ethnicities"},
        ),
        migrations.AlterModelOptions(
            name="fieldofresearch",
            options={"verbose_name_plural": "fields of research"},
        ),
        migrations.AlterModelOptions(
            name="fieldofstudy",
            options={"ordering": ["description"], "verbose_name_plural": "fields of study"},
        ),
        migrations.AddField(
            model_name="affiliation",
            name="qualification",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="historicalaffiliation",
            name="qualification",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="affiliation",
            name="role",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="historicalaffiliation",
            name="role",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="historicalprofile",
            name="education_level",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "No Qualification"),
                    (1, "Level 1 Certificate"),
                    (2, "Level 2 Certificate"),
                    (3, "Level 3 Certificate"),
                    (4, "Level 4 Certificate"),
                    (5, "Level 5 Diploma/Certificate"),
                    (6, "Level 6 Graduate Certificate, Level 6 Diploma/Certificate"),
                    (
                        7,
                        "Bachelor Degree, Level 7 Graduate Diploma/Certificate, Level 7 Diploma/ Certificate",
                    ),
                    (8, "Postgraduate Diploma/Certificate, Bachelor Honours"),
                    (9, "Masters Degree"),
                    (10, "Doctorate Degree"),
                    (23, "Overseas Secondary School Qualification"),
                    (94, "Don't Know"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalprofile",
            name="employment_status",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Paid employee"),
                    (2, "Employer"),
                    (3, "Self-employed and without employees"),
                    (4, "Unpaid family worker"),
                    (6, "Student"),
                    (5, "Not stated"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="education_level",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "No Qualification"),
                    (1, "Level 1 Certificate"),
                    (2, "Level 2 Certificate"),
                    (3, "Level 3 Certificate"),
                    (4, "Level 4 Certificate"),
                    (5, "Level 5 Diploma/Certificate"),
                    (6, "Level 6 Graduate Certificate, Level 6 Diploma/Certificate"),
                    (
                        7,
                        "Bachelor Degree, Level 7 Graduate Diploma/Certificate, Level 7 Diploma/ Certificate",
                    ),
                    (8, "Postgraduate Diploma/Certificate, Bachelor Honours"),
                    (9, "Masters Degree"),
                    (10, "Doctorate Degree"),
                    (23, "Overseas Secondary School Qualification"),
                    (94, "Don't Know"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="employment_status",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Paid employee"),
                    (2, "Employer"),
                    (3, "Self-employed and without employees"),
                    (4, "Unpaid family worker"),
                    (6, "Student"),
                    (5, "Not stated"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profilecareerstage",
            name="year_achieved",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Year that you first attained the career stage",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
    ]
