# Generated by Django 3.0.7 on 2020-07-09 10:12

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portal", "0010_member_role"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="affiliations",),
        migrations.RunSQL(
            """
            ALTER TABLE application ADD COLUMN state varchar(50) DEFAULT 'new'  NULL;
            ALTER TABLE application_history ADD COLUMN state varchar(50) DEFAULT 'new' NULL;
            ALTER TABLE application ADD COLUMN "file" varchar(100) NULL;
            ALTER TABLE application_history ADD COLUMN "file" varchar(100) NULL;
            """,
            "",
            state_operations=[
                migrations.AddField(
                    model_name="application",
                    name="state",
                    field=django_fsm.FSMField(default="new", max_length=50),
                ),
                migrations.AddField(
                    model_name="historicalapplication",
                    name="state",
                    field=django_fsm.FSMField(default="new", max_length=50),
                ),
                migrations.AddField(
                    model_name="application",
                    name="file",
                    field=private_storage.fields.PrivateFileField(
                        blank=True,
                        null=True,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="",
                    ),
                ),
                migrations.AddField(
                    model_name="historicalapplication",
                    name="file",
                    field=models.TextField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="invitation",
            name="invitee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="affiliation",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="affiliations",
                to="portal.Profile",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="has_authorized",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nominee",
            name="title",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name="Testimony",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "file",
                    private_storage.fields.PrivateFileField(
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="",
                    ),
                ),
                ("state", django_fsm.FSMField(default="new", max_length=50)),
                (
                    "referee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimony",
                        to="portal.Referee",
                    ),
                ),
            ],
            options={"ordering": ["-id"], "abstract": False, "db_table": "testimony",},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Nomination",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.CharField(blank=True, max_length=40, null=True)),
                ("email", models.EmailField(max_length=254, verbose_name="email address")),
                ("first_name", models.CharField(max_length=30)),
                (
                    "middle_names",
                    models.CharField(
                        blank=True,
                        help_text="Comma separated list of middle names",
                        max_length=280,
                        null=True,
                        verbose_name="middle names",
                    ),
                ),
                ("last_name", models.CharField(max_length=150)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "file",
                    private_storage.fields.PrivateFileField(
                        blank=True,
                        help_text="Upload filled-in nominator form",
                        null=True,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="",
                        verbose_name="Nominator form",
                    ),
                ),
                ("state", django_fsm.FSMField(default="new", max_length=50)),
                (
                    "application",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nomination",
                        to="portal.Application",
                    ),
                ),
                (
                    "nominator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.Organisation",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominations",
                        to="portal.Round",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nominations_to_apply",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "nomination",},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AddField(
            model_name="invitation",
            name="nomination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="portal.Nomination",
            ),
        ),
    ]
