# Generated by Django 3.0.5 on 2020-04-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20200412_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='primary_language_spoken',
            field=models.CharField(blank=True, choices=[('English (New Zealand English)', 'English (New Zealand English)'), ('Māori', 'Māori'), ('Samoan', 'Samoan'), ('Hindi', 'Hindi'), ('Mandarin Chinese', 'Mandarin Chinese'), ('French', 'French'), ('Yue Chinese (Cantonese)', 'Yue Chinese (Cantonese)'), ('Chinese (not further defined)', 'Chinese (not further defined)'), ('German', 'German'), ('Tongan', 'Tongan'), ('Tagalog', 'Tagalog'), ('Afrikaans', 'Afrikaans'), ('Spanish', 'Spanish'), ('Korean', 'Korean'), ('Dutch', 'Dutch'), ('New Zealand Sign Language', 'New Zealand Sign Language'), ('Japanese', 'Japanese'), ('Punjabi', 'Punjabi'), ('Gujarati', 'Gujarati'), ('Arabic', 'Arabic'), ('Russian', 'Russian'), ('Italian', 'Italian'), ('Cook Islands Māori', 'Cook Islands Māori'), ('Thai', 'Thai'), ('Tamil', 'Tamil'), ('Malaysian', 'Malaysian'), ('Khmer', 'Khmer'), ('Fijian', 'Fijian'), ('Vietnamese', 'Vietnamese'), ('Serbo-Croatian', 'Serbo-Croatian'), ('Sinhala', 'Sinhala'), ('Min Chinese', 'Min Chinese'), ('Persian', 'Persian'), ('Urdu', 'Urdu'), ('Bahasa Indonesia', 'Bahasa Indonesia'), ('Niuean', 'Niuean'), ('Malayalam', 'Malayalam'), ('Other', 'Other')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='primary_language_spoken',
            field=models.CharField(blank=True, choices=[('English (New Zealand English)', 'English (New Zealand English)'), ('Māori', 'Māori'), ('Samoan', 'Samoan'), ('Hindi', 'Hindi'), ('Mandarin Chinese', 'Mandarin Chinese'), ('French', 'French'), ('Yue Chinese (Cantonese)', 'Yue Chinese (Cantonese)'), ('Chinese (not further defined)', 'Chinese (not further defined)'), ('German', 'German'), ('Tongan', 'Tongan'), ('Tagalog', 'Tagalog'), ('Afrikaans', 'Afrikaans'), ('Spanish', 'Spanish'), ('Korean', 'Korean'), ('Dutch', 'Dutch'), ('New Zealand Sign Language', 'New Zealand Sign Language'), ('Japanese', 'Japanese'), ('Punjabi', 'Punjabi'), ('Gujarati', 'Gujarati'), ('Arabic', 'Arabic'), ('Russian', 'Russian'), ('Italian', 'Italian'), ('Cook Islands Māori', 'Cook Islands Māori'), ('Thai', 'Thai'), ('Tamil', 'Tamil'), ('Malaysian', 'Malaysian'), ('Khmer', 'Khmer'), ('Fijian', 'Fijian'), ('Vietnamese', 'Vietnamese'), ('Serbo-Croatian', 'Serbo-Croatian'), ('Sinhala', 'Sinhala'), ('Min Chinese', 'Min Chinese'), ('Persian', 'Persian'), ('Urdu', 'Urdu'), ('Bahasa Indonesia', 'Bahasa Indonesia'), ('Niuean', 'Niuean'), ('Malayalam', 'Malayalam'), ('Other', 'Other')], max_length=40, null=True),
        ),
    ]
