# Generated by Django 3.2.8 on 2021-10-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0011_auto_20211029_1257"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalround",
            name="closes_on",
            field=models.DateTimeField(blank=True, null=True, verbose_name="closes on"),
        ),
        migrations.AlterField(
            model_name="round",
            name="closes_on",
            field=models.DateTimeField(blank=True, null=True, verbose_name="closes on"),
        ),
    ]
