# Generated by Django 3.0.8 on 2020-07-19 11:52

from django.db import migrations, models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_nominations_and_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referee',
            name='has_testifed',
            field=models.BooleanField(blank=True, null=True),
        )
    ]
