# Generated by Django 3.2.9 on 2022-02-25 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0004_auto_20210331_1418"),
        ("portal", "0012_auto_20211030_1531"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalround",
            name="site",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sites.site",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="site",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="sites.site"
            ),
        ),
        migrations.AddField(
            model_name="scheme",
            name="site",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="sites.site"
            ),
        ),
    ]
