# Generated by Django 3.0.5 on 2020-04-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20200416_0712'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscription',
            table='subscription',
        ),
    ]
