# Generated by Django 3.0.8 on 2020-08-11 11:20

from django.db import migrations, models
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20200811_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_verification', to='portal.Application'),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='file',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='', verbose_name='Photo Identity'),
        ),
    ]
