# Generated by Django 3.0.8 on 2020-08-21 10:47

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0016_auto_20200811_2320"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identityverification",
            name="state",
            field=django_fsm.FSMField(db_index=True, default="new", max_length=50),
        ),
    ]
