# Generated by Django 3.0.10 on 2020-09-13 06:51

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0016_auto_20200826_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCriterion',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('definition', models.TextField(max_length=200)),
                ('definition_en', models.TextField(max_length=200, null=True)),
                ('definition_mi', models.TextField(max_length=200, null=True)),
                ('comment', models.BooleanField(default=True, help_text='The pannelist should commnet their score')),
                ('scale', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='portal.Round')),
            ],
            options={
                'verbose_name': 'historical criterion',
                'db_table': 'criterion_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('definition', models.TextField(max_length=200)),
                ('definition_en', models.TextField(max_length=200, null=True)),
                ('definition_mi', models.TextField(max_length=200, null=True)),
                ('comment', models.BooleanField(default=True, help_text='The pannelist should commnet their score')),
                ('scale', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='portal.Round')),
            ],
            options={
                'db_table': 'criterion',
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
    ]
