# Generated by Django 3.0.10 on 2020-09-20 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20200913_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='portal.Round'),
        ),
        migrations.AlterField(
            model_name='panelist',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='panelists', to='portal.Round'),
        ),
    ]
