# Generated by Django 3.0.5 on 2020-04-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20200416_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprofile',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ethnicity',
        ),
        migrations.AddField(
            model_name='profile',
            name='ethnicity',
            field=models.ManyToManyField(to='portal.Ethnicity'),
        ),
    ]
