# Generated by Django 3.0.5 on 2020-04-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20200416_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ethnicity',
            field=models.ManyToManyField(db_table='profile_ethnicity', to='portal.Ethnicity'),
        ),
    ]
