# Generated by Django 3.0.10 on 2020-10-05 12:02

from django.db import migrations, models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("portal", "0020_maillog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="criterion",
            options={"verbose_name_plural": "criteria"},
        ),
        migrations.RunSQL(
            """
            SET sql_mode='ANSI_QUOTES';
            ALTER TABLE round ADD COLUMN has_online_scoring BOOL DEFAULT true;
            ALTER TABLE round_history ADD COLUMN has_online_scoring BOOL DEFAULT true;
            """,
            "",
            state_operations=[
                migrations.AddField(
                    model_name="historicalround",
                    name="has_online_scoring",
                    field=models.BooleanField(default=True),
                ),
                migrations.AddField(
                    model_name="round",
                    name="has_online_scoring",
                    field=models.BooleanField(default=True),
                ),
            ]
        ),
    ]
