# Generated by Django 3.0.5 on 2020-04-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_auto_20200416_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethnicity',
            name='description',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='level_one_description',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='level_three_description',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='level_two_description',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='historicalethnicity',
            name='description',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='historicalethnicity',
            name='level_one_description',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='historicalethnicity',
            name='level_three_description',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='historicalethnicity',
            name='level_two_description',
            field=models.CharField(max_length=40),
        ),
    ]
