# Generated by Django 3.0.10 on 2020-10-15 06:30

from django.db import migrations, models
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("portal", "0022_auto_20201007_0045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="criterion",
            name="comment",
            field=models.BooleanField(
                default=True, help_text="The panelist should comment their score"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcriterion",
            name="comment",
            field=models.BooleanField(
                default=True, help_text="The panelist should comment their score"
            ),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="application",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identity_verification",
                to="portal.Application",
            ),
        ),
        migrations.AlterField(
            model_name="profilepersonidentifier",
            name="value",
            field=models.CharField(max_length=100),
        ),
    ]
