# Generated by Django 3.0.5 on 2020-04-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_auto_20200417_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='sex',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Undisclosed'), (1, 'Male'), (2, 'Female'), (3, 'Gender diverse')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Undisclosed'), (1, 'Male'), (2, 'Female'), (3, 'Gender diverse')], null=True),
        ),
    ]
