# Generated by Django 3.0.5 on 2020-04-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_auto_20200417_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallanguage',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ethnicities',
            field=models.ManyToManyField(blank=True, db_table='profile_ethnicity', to='portal.Ethnicity'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages_spoken',
            field=models.ManyToManyField(blank=True, db_table='profile_language', to='portal.Language'),
        ),
    ]
