# Generated by Django 3.1.7 on 2021-03-31 01:18

import django.core.validators
from django.db import migrations, models

import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0032_auto_20210303_1514"),
    ]

    operations = [
        migrations.RunSQL("DROP VIEW IF EXISTS scheme_application_view;", ""),
        migrations.AddField(
            model_name="historicalround",
            name="score_sheet_template",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["xls", "xlsx"]
                    )
                ],
                verbose_name="Score Sheet Template",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="score_sheet_template",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=portal.models.round_score_sheet_template_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["xls", "xlsx"]
                    )
                ],
                verbose_name="Score Sheet Template",
            ),
        ),
    ]
