# Generated by Django 3.0.5 on 2020-04-22 01:35

import common.models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portal", "0033_auto_20200421_0952"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalOrganisation",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=200)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical organisation",
                "db_table": "organisation_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("email", models.EmailField(max_length=254, verbose_name="email address")),
                ("name", models.CharField(max_length=150, verbose_name="full name")),
                ("organisation", models.CharField(max_length=200, verbose_name="organisation")),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[
                            ("draft", "draft"),
                            ("submitted", "submitted"),
                            ("accepted", "accepted"),
                            ("expired", "expired"),
                        ],
                        default="draft",
                        max_length=100,
                        no_check_for_status=True,
                    ),
                ),
                (
                    "submitted_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", when={"submitted"}
                    ),
                ),
                (
                    "accepted_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", when={"accepted"}
                    ),
                ),
                (
                    "expired_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", when={"expired"}
                    ),
                ),
            ],
            options={"db_table": "invitation",},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={"db_table": "organisation",},
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.RemoveField(model_name="historicallanguage", name="history_user",),
        migrations.AlterModelTable(name="historicalapplication", table="application_history",),
        migrations.AlterModelTable(name="historicalprofile", table="profile_history",),
        migrations.AlterModelTable(name="historicalsubscription", table="subscription_history",),
        migrations.DeleteModel(name="HistoricalEthnicity",),
        migrations.DeleteModel(name="HistoricalLanguage",),
        migrations.AddField(
            model_name="invitation",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portal.Organisation",
                verbose_name="organisation",
            ),
        ),
    ]
