# Generated by Django 3.0.5 on 2020-04-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0040_iwigroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='iwi_groups',
            field=models.ManyToManyField(blank=True, db_table='profile_iwi_group', to='portal.IwiGroup'),
        ),
    ]
