# Generated by Django 3.0.5 on 2020-04-28 14:06

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0041_profile_iwi_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgIdentifierType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(max_length=2, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=20)),
                ("definition", models.TextField(max_length=200)),
            ],
            options={"db_table": "org_identifier_type", "ordering": ["code"],},
            bases=(common.models.HelperMixin, models.Model),
        ),
    ]
