# Generated by Django 3.0.5 on 2020-05-01 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0047_auto_20200501_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Organisation', verbose_name='organisation'),
        ),
        migrations.AlterField(
            model_name='historicalaffiliation',
            name='org',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='portal.Organisation', verbose_name='organisation'),
        ),
    ]
