# Generated by Django 3.0.6 on 2020-05-06 02:22

from django.db import migrations, models
import model_utils.fields
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0052_auto_20200506_1319"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="accepted_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="status", null=True, when={"accepted"}
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="expired_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="status", null=True, when={"expired"}
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="submitted_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="status", null=True, when={"submitted"}
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="token",
            field=models.CharField(
                default=portal.models.get_unique_invitation_token, max_length=42, unique=True
            ),
        ),
    ]
