# Generated by Django 3.0.6 on 2020-05-09 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0059_recognition_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recognition",
            name="award",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="portal.Award"
            ),
        ),
    ]
