# Generated by Django 3.0.6 on 2020-05-12 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0062_auto_20200511_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'permissions': (('can_invite', 'Can invite a user to join the portal or grant a role'),)},
        ),
    ]
