# Generated by Django 3.0.6 on 2020-05-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0078_auto_20200528_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalround',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
