# Generated by Django 3.0.6 on 2020-05-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0083_auto_20200530_0503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalScheme',
        ),
    ]
