# Generated by Django 3.0.6 on 2020-05-31 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0085_auto_20200530_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrecord',
            name='put_code',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.FieldOfStudy'),
        ),
    ]
