# Generated by Django 3.0.6 on 2020-06-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0095_auto_20200606_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectionpattern',
            name='description_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='protectionpattern',
            name='description_mi',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
