# Generated by Django 3.0.6 on 2020-06-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0096_auto_20200606_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectionpattern',
            name='code',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
