# Generated by Django 3.0.6 on 2020-06-06 12:58

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0097_auto_20200606_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprofile',
            name='protection_pattern',
        ),
        migrations.RemoveField(
            model_name='historicalprofile',
            name='protection_pattern_expires_on',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='protection_pattern',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='protection_pattern_expires_on',
        ),
        migrations.AddField(
            model_name='historicalprofile',
            name='has_protection_patterns',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_protection_patterns',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProfileProtectionPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Profile')),
                ('protection_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.ProtectionPattern')),
            ],
            options={
                'db_table': 'profile_protection_pattern',
                'unique_together': {('profile', 'protection_pattern')},
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
    ]
