# Generated by Django 3.0.6 on 2020-06-08 22:44

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0098_auto_20200607_0058"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileprotectionpattern",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_protection_patterns",
                to="portal.Profile",
            ),
        ),
        migrations.AlterField(
            model_name="profileprotectionpattern",
            name="protection_pattern",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_protection_patterns",
                to="portal.ProtectionPattern",
            ),
        ),
        migrations.RunSQL(
            """
            CREATE VIEW protection_pattern_profile_view AS
            SELECT
                pp.description,
                pp.pattern,
                pp.description_en,
                pp.description_mi,
                pp.code,
                ppp.expires_on,
                ppp.profile_id,
                ppp.created_at,
                ppp.updated_at
            FROM protection_pattern AS pp
            LEFT JOIN profile_protection_pattern AS ppp ON ppp.protection_pattern_id=pp.code;
            """,
            "DROP VIEW IF EXISTS protection_pattern_profile_view;",
            state_operations=[
                migrations.CreateModel(
                    name="ProtectionPatternProfie",
                    fields=[
                        ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                        ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                        (
                            "code",
                            models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                        ),
                        ("description", models.CharField(max_length=80)),
                        ("pattern", models.CharField(max_length=80)),
                        ("expires_on", models.DateField(blank=True, null=True)),
                    ],
                    options={
                        "db_table": "protection_pattern_profile_view",
                        "ordering": ["description"],
                        "managed": False,
                    },
                    bases=(common.models.HelperMixin, models.Model),
                )
            ],
        ),
        migrations.RunSQL(
            """
            CREATE VIEW IF NOT EXISTS protection_pattern_profile_view AS
            SELECT
                pp.description,
                pp.pattern,
                pp.description_en,
                pp.description_mi,
                pp.code,
                ppp.expires_on,
                ppp.profile_id,
                ppp.created_at,
                ppp.updated_at
            FROM protection_pattern AS pp
            LEFT JOIN profile_protection_pattern AS ppp ON ppp.protection_pattern_id=pp.code;
            """,
            "DROP VIEW IF EXISTS protection_pattern_profile_view;",
            state_operations=[
                migrations.CreateModel(
                    name="ProtectionPatternProfile",
                    fields=[
                        ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                        ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                        (
                            "code",
                            models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                        ),
                        ("description", models.CharField(max_length=80)),
                        ("pattern", models.CharField(max_length=80)),
                        ("expires_on", models.DateField(blank=True, null=True)),
                    ],
                    options={
                        "db_table": "protection_pattern_profile_view",
                        "ordering": ["description"],
                        "managed": False,
                    },
                    bases=(common.models.HelperMixin, models.Model),
                )
            ],
        ),
    ]
