# Generated by Django 3.0.6 on 2020-06-10 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0099_auto_20200609_1151'),
        ('portal', '0096_auto_20200608_2319'),
    ]

    operations = [
    ]
