# Generated by Django 2.2.12 on 2020-04-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_historicaluser"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="orcid",
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name="ORCID iD"),
        ),
        migrations.AddField(
            model_name="user",
            name="orcid",
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name="ORCID iD"),
        ),
    ]
