# Generated by Django 3.0.5 on 2020-04-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20200421_0953"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Name of User"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Name of User"
            ),
        ),
    ]
