# Generated by Django 3.0.6 on 2020-06-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20200605_0208"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="middle_names",
            field=models.CharField(
                blank=True,
                help_text="Comma separated list of middle names",
                max_length=280,
                null=True,
                verbose_name="middle names",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="middle_names",
            field=models.CharField(
                blank=True,
                help_text="Comma separated list of middle names",
                max_length=280,
                null=True,
                verbose_name="middle names",
            ),
        ),
    ]
