# Generated by Django 3.0.7 on 2020-06-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200605_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Is Approved'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Is Approved'),
        ),
    ]
