# Generated by Django 3.0.8 on 2020-08-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_auto_20200728_2203"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MR", "Mr"),
                    ("MRS", "Mrs"),
                    ("MS", "Ms"),
                    ("DR", "Dr"),
                    ("PROF", "Prof"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MR", "Mr"),
                    ("MRS", "Mrs"),
                    ("MS", "Ms"),
                    ("DR", "Dr"),
                    ("PROF", "Prof"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
