# Generated by Django 3.1.7 on 2021-03-31 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_org_and_scheme_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="first name"),
        ),
    ]
