# Generated by Django 3.0.5 on 2020-04-11 11:34

from django.db import migrations
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bod',
            field=partial_date.fields.PartialDateField(blank=True, null=True, verbose_name='date of birth'),
        ),
    ]
