# Generated by Django 3.0.5 on 2020-04-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20200412_0555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
