# Generated by Django 3.0.5 on 2020-04-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20200416_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ethnicity',
            options={'ordering': ['code']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='ethnicity',
            new_name='ethnicities',
        ),
    ]
