# Generated by Django 2.2.12 on 2020-04-18 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_auto_20200417_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Privace Policy Accepted'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Privace Policy Accepted'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
