# Generated by Django 3.0.5 on 2020-04-23 14:49

import secrets

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0035_auto_20200421_2057"),
    ]

    operations = [
        migrations.RemoveField(model_name="invitation", name="name",),
        migrations.AddField(
            model_name="invitation",
            name="first_name",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invitation",
            name="last_name",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invitation",
            name="token",
            field=models.CharField(
                default=lambda: secrets.token_urlsafe(8), max_length=8, unique=True
            ),
        ),
    ]
