# Generated by Django 3.0.5 on 2020-04-28 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0042_orgidentifiertype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgidentifiertype',
            options={'ordering': ['code'], 'verbose_name': 'organisation identifier type'},
        ),
        migrations.AddField(
            model_name='application',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Organisation'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='org',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='portal.Organisation'),
        ),
    ]
