# Generated by Django 3.0.6 on 2020-05-09 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0057_award_recognition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={},
        ),
        migrations.AlterModelTable(
            name='award',
            table='award',
        ),
    ]
