# Generated by Django 3.0.6 on 2020-05-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0061_auto_20200510_2124"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="organisation",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="organisation"
            ),
        ),
    ]
