# Generated by Django 3.0.6 on 2020-05-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0069_auto_20200518_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='is_ethnicities_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='is_iwi_groups_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_ethnicities_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_iwi_groups_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recognition',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
