# Generated by Django 3.0.6 on 2020-05-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0070_auto_20200520_0051'),
        ('portal', '0070_auto_20200520_0109'),
    ]

    operations = [
    ]
