# Generated by Django 3.0.6 on 2020-05-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0077_auto_20200528_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalround',
            old_name='open_on',
            new_name='opens_on',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='open_on',
            new_name='opens_on',
        ),
    ]
