# Generated by Django 3.0.6 on 2020-05-31 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0085_auto_20200530_0554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalSubscription',
        ),
    ]
