# Generated by Django 3.0.6 on 2020-06-01 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0086_delete_historicalsubscription'),
        ('portal', '0087_auto_20200601_0233'),
    ]

    operations = [
    ]
