# Generated by Django 3.0.6 on 2020-06-04 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0091_auto_20200604_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrecord',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Qualification'),
        ),
    ]
